# Generated by Django 4.0 on 2021-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('path', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
