# Generated by Django 4.0 on 2021-12-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_stream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url',
            new_name='author',
        ),
    ]
